name: CI Build

on: [ push, pull_request_target ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # test with LTS version and latest
        java: [ 11, 15 ]
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK ${{ matrix.java }}
        uses: cescoffier/setup-jdk@v1
        with:
          java-version: ${{ matrix.java }}
          architecture: 'x64'

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Build with Gradle
        run: ./gradlew build test

      - uses: ashley-taylor/junit-report-annotations-action@master
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
        if: always()
